
---
- name: Loops Playbook
  hosts: all
  become: yes

  vars:
    source_file: ./my_web_site/index.html
    destin_file: /var/www/html

  tasks:
  - name: Say Hello to ALL
    debug: msg="Hello {{ item }}"
    loop:
      - "one"
      - "two"
      - "three"

  - name: Loop until example
    shell: echo -n A >> myfile.txt && cat myfile.txt
    register: output
    delay: 2 # 2 seconds
    retries: 10
    until: output.stdout.find("AAAA") == false

  - name: print output
    debug:
      var: output.stdout

  - name: Install many packaged # just example
    yum: name={{ item }} state=installed
    with_items: # or loop:
      - python
      - tree
      - mysql-client